# This example demonstrates the loading of a hard-wired input artifact from a GCP storage.
#
# It uses a GCP Service Account Key stored as a regular Kubernetes secret, to access GCP storage.
# To create the secret required for this example, first run the following command:
#
# $ kubectl create secret generic my-gcs-credentials --from-file=serviceAccountKey=<YOUR-SERVICE-ACCOUNT-KEY-file>
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-gcs-
spec:
  entrypoint: input-artifact-gcs-example
  templates:
    - name: input-artifact-gcs-example
      inputs:
        artifacts:
          - name: my-art
            path: /my-artifact
            s3:
              endpoint: obs.cn-north-4.myhuaweicloud.com
              bucket: mlops-example-bucket
              # key could be either a file or a directory.
              key: hello_world
              accessKeySecret:
                name: mlops-bucket-serviceaccount
                key: accessKey
              secretKeySecret:
                name: mlops-bucket-serviceaccount
                key: secretKey
      container:
        image: debian:latest
        command: [sh, -c]
        args: ["ls -l /my-artifact"]
